

// ********RoostGPT********
/*
Test generated by RoostGPT for test nov-26-gradle using AI Type Claude AI and AI Model claude-opus-4-5-20251101

ROOST_METHOD_HASH=createCustomer_125e4a940b
ROOST_METHOD_SIG_HASH=createCustomer_23da971a1e

Scenario 1: Successfully Create a Valid Customer

Details:
  TestName: createCustomerWithValidData
  Description: Verify that the createCustomer method successfully saves a valid Customer object and returns the saved customer with all properties intact.

Execution:
  Arrange: Create a mock CustomerRepository. Create a valid Customer object with appropriate data. Configure the mock repository's save method to return the same customer object.
  Act: Call the createCustomer method with the valid Customer object.
  Assert: Verify that the returned Customer is not null and matches the input customer. Verify that the repository's save method was called exactly once with the customer parameter.

Validation:
  This assertion verifies that the createCustomer method correctly delegates to the repository's save method and returns the persisted customer. This is fundamental to ensuring that customer data is properly stored in the database.

---

Scenario 2: Create Customer with Null Input

Details:
  TestName: createCustomerWithNullInput
  Description: Test the behavior of createCustomer when a null Customer object is passed as input, verifying how the method handles null values.

Execution:
  Arrange: Create a mock CustomerRepository. Configure the mock repository's save method to handle null input (either return null or throw an exception based on repository behavior).
  Act: Call the createCustomer method with null as the parameter.
  Assert: Verify the behavior matches the expected outcome - either a null return value or an exception is thrown.

Validation:
  This test validates the method's behavior when receiving invalid null input. Understanding this edge case is important for error handling and ensuring the application doesn't fail unexpectedly when receiving malformed requests.

---

Scenario 3: Create Customer When Repository Throws Exception

Details:
  TestName: createCustomerWhenRepositoryThrowsException
  Description: Verify that the createCustomer method properly propagates exceptions thrown by the underlying repository during the save operation.

Execution:
  Arrange: Create a mock CustomerRepository. Create a valid Customer object. Configure the mock repository's save method to throw a RuntimeException (simulating a database error).
  Act: Call the createCustomer method with the Customer object.
  Assert: Verify that the exception is propagated and the same exception type is thrown.

Validation:
  This test ensures that database-level errors are properly propagated up the call stack, allowing higher layers to handle them appropriately. This is critical for maintaining proper error handling throughout the application.

---

Scenario 4: Create Customer and Verify Repository Interaction

Details:
  TestName: createCustomerVerifiesRepositorySaveIsCalled
  Description: Confirm that the createCustomer method correctly invokes the repository's save method with the exact Customer object provided.

Execution:
  Arrange: Create a mock CustomerRepository. Create a Customer object with specific data.
  Act: Call the createCustomer method with the Customer object.
  Assert: Verify using mock verification that customerRepository.save() was called exactly once with the exact Customer object passed to createCustomer.

Validation:
  This test validates the correct integration between the service layer and the repository layer. It ensures that the service properly delegates persistence operations to the repository without modifying the customer data.

---

Scenario 5: Create Customer Returns Repository Response

Details:
  TestName: createCustomerReturnsExactRepositoryResponse
  Description: Verify that the createCustomer method returns exactly what the repository's save method returns, without any modification.

Execution:
  Arrange: Create a mock CustomerRepository. Create an input Customer object and a separate saved Customer object (potentially with an assigned ID). Configure the mock repository's save method to return the saved Customer object.
  Act: Call the createCustomer method with the input Customer object.
  Assert: Verify that the returned Customer is the exact same object reference returned by the repository's save method.

Validation:
  This test confirms that the service layer acts as a transparent pass-through for the repository response. This is important for ensuring that any modifications made by the repository (such as ID assignment or timestamp updates) are properly returned to the caller.

*/

// ********RoostGPT********

package com.example.demo.service;
import com.example.demo.domain.Customer;
import com.example.demo.domain.CustomerRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import org.junit.jupiter.api.*;
import org.springframework.stereotype.Service;
import java.util.List;
import java.util.Optional;

@ExtendWith(MockitoExtension.class)
class CustomerServiceCreateCustomerTest {
    @Mock
    private CustomerRepository customerRepository;
    private CustomerService customerService;
    @BeforeEach
    void setUp() {
        customerService = new CustomerService(customerRepository);
    }
    @Test
    @Tag("valid")
    void createCustomerWithValidData() {
        // Arrange
        Customer customer = new Customer();
        when(customerRepository.save(customer)).thenReturn(customer);
        // Act
        Customer result = customerService.createCustomer(customer);
        // Assert
        assertNotNull(result);
        assertSame(customer, result);
        verify(customerRepository, times(1)).save(customer);
    }
    @Test
    @Tag("invalid")
    void createCustomerWithNullInput() {
        // Arrange
        when(customerRepository.save(null)).thenReturn(null);
        // Act
        Customer result = customerService.createCustomer(null);
        // Assert
        assertNull(result);
        verify(customerRepository, times(1)).save(null);
    }
    @Test
    @Tag("invalid")
    void createCustomerWhenRepositoryThrowsException() {
        // Arrange
        Customer customer = new Customer();
        RuntimeException expectedException = new RuntimeException("Database error");
        when(customerRepository.save(customer)).thenThrow(expectedException);
        // Act & Assert
        RuntimeException thrownException = assertThrows(RuntimeException.class, () -> {
            customerService.createCustomer(customer);
        });
        assertEquals("Database error", thrownException.getMessage());
        verify(customerRepository, times(1)).save(customer);
    }
    @Test
    @Tag("integration")
    void createCustomerVerifiesRepositorySaveIsCalled() {
        // Arrange
        Customer customer = new Customer();
        when(customerRepository.save(customer)).thenReturn(customer);
        // Act
        customerService.createCustomer(customer);
        // Assert
        verify(customerRepository, times(1)).save(customer);
        verifyNoMoreInteractions(customerRepository);
    }
    @Test
    @Tag("valid")
    void createCustomerReturnsExactRepositoryResponse() {
        // Arrange
        Customer inputCustomer = new Customer();
        Customer savedCustomer = new Customer();
        when(customerRepository.save(inputCustomer)).thenReturn(savedCustomer);
        // Act
        Customer result = customerService.createCustomer(inputCustomer);
        // Assert
        assertSame(savedCustomer, result);
        assertNotSame(inputCustomer, result);
        verify(customerRepository, times(1)).save(inputCustomer);
    }
}